### ISSUE TITLE
Error ce-36441-8 on ps4 no matter what

### ISSUE THREAD

**Issue by EnekoT2001** [Gkiokan/ps4-remote-pkg-sender#12]
Basically, every time I try to send a package it only sends til the "ready to play" chunk and it thinks that's 100% so the program says "finished" but it gives me an error saying it cant install it on the ps4 (probably bc it tries to finish it up and start with the next playgo chunk and the program thinks its done so it doesn't send?).

I have a ps4 pro on 9.00 with goldhen2.0b2 connected via ethernet to my pc and i tried with both versions of the tool and nothing. I leave RPI on screen the whole time, i tried rebooting, trying a different server IP address, using wifi too, nothing gets it to work ever.

This also happens with every other package sender tool I could find, I'm starting to think all this is just a myth tbh.
Also the PS4 OS has been reinstalled recently, i started from scratch aka full wipe and reinstall to jailbreak it and all and have my profile activated and such so idk why i keep getting this error?

**Comment by Masamune3210** [comment]
If it happens with every sender its either a issue with your setup or your console, have no idea what would be causing it to end early like that though

**Comment by Gkiokan** [comment]
The error ce-36441-8 seems to be related to the pkg file itself. 
Try to check the pkg file with a PkGEditor. 

If you google a bit about the error they say it is either a corrupt file or an update file from a retail pkg.

**Comment by EnekoT2001** [comment]
> The error ce-36441-8 seems to be related to the pkg file itself. Try to check the pkg file with a PkGEditor.
> 
> If you google a bit about the error they say it is either a corrupt file or an update file from a retail pkg.
> 
> Here some researches On Reddit [https://www.reddit.com/r/ps4homebrew.../](https://www.reddit.com/r/ps4homebrew/comments/a4hxex/remote_installer_ce364418/)
> 
> On Google [https://www.google.com/search?q=ce-36441-8....](https://www.google.com/search?q=ce-36441-8+ps4&sxsrf=AOaemvKKw7qx2p4dpGew8AgOSo11XU1Msw%3A1642272652348&ei=jBfjYeniFMyTxc8Pwuay6AE&ved=0ahUKEwjp2MSwtrT1AhXMSfEDHUKzDB0Q4dUDCA4&uact=5&oq=ce-36441-8+ps4&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgYIABAWEB46BwgAEEcQsAM6BwgAELADEEM6BAgAEB46CAgAEAUQChAeSgQIQRgASgQIRhgAUMgBWLgEYOsFaAFwAngAgAH5AYgB-gSSAQUwLjMuMZgBAKABAcgBCcABAQ&sclient=gws-wiz)
> 
> On psxhax https://www.psxhax.com/threads/ps4-error-ce-36441-8.8864/

It's not the pkg file, it checks out fine on every pkg checker program and installs fine through USB, and i tried several games too, all the same error in the same fashion.

**Comment by Gkiokan** [comment]
Maybe it has something to do with your network settings?  

I had another user that got timeout error just because of his network settings even the ps4 check was successfull.

**Comment by EnekoT2001** [comment]
> Maybe it has something to do with your network settings?
> 
> I had another user that got timeout error just because of his network settings even the ps4 check was successfull.

I triple checked the IP, I'm using ethernet, also tried with wi-fi, different ports, opened them in the router, changed ips and such, nothing seems to change the behavior at all :(

**Comment by Gkiokan** [comment]
If you get the error even with different pkg sender, you may try to post that on psxhax.  
Maybe they have a solution out of the box or any other user is facing that issue, too.  

Maybe it has something to do with GoldHen? Try HEN if possible. I am still on 5.05.  

One last thing I can offer is I could remote to your pc and try to run the tool in dev mode to see what the RPI says at all.  
Or you try yourself. git clone the project and run it with `npm i && npm run dev` 

Message me on Discord if you want me to try Gkiokan#0735

**Comment by EnekoT2001** [comment]
Ok i did that and checked the logs and such and all it shows is that it started installing and then updated the info/state of it til it appeared as finished, that's all. I think it might be on the ps4 side but i literally don't know what might be causing the issue since everything else seems to work ok, i could try with mira later maybe or HEN, but I'm on 9.00 maybe that has something to do?
Thanks for all the help though

**Comment by Gkiokan** [comment]
Maybe it have something to do with the latest GoldHEN version. Try HEN.  
If that doesn't work try to run the dev mode as described and look what the RPI responds to you.  

Even when I build every error catcher in that is possible there is one error that shouldn't appear excactly that one is not logged. However you will see it then in the devTools if you look into the console. Keep an eye on that.  

![image](https://user-images.githubusercontent.com/7249224/149640201-6d4eeba0-5a65-4b9c-b565-19000857b34a.png)

**Comment by EnekoT2001** [comment]
Ok, I'll try to use HEN tomorrow and if not ill try to run it in dev mode (i still don't know how exactly tho but I'll figure it out) and I'll update you here or on discord depending on how confusing it is, thanks again!

**Comment by Masamune3210** [comment]
Works fine for me on 9.00 on latest GoldHEN, so idk

**Comment by Gkiokan** [comment]
If anyone else is facing this Issue try using the PIP Installer way. Modded Warefare have a tutorial on that.  
  
The problem here belongs to the PS4 and the RPI on it and not to my tool.  
I have tried to debug that error down, but it is not possible.  RPI just don't do anything with the install request or 
it odes something differently or crashes.  It may be caused though any payloads that will be loaded, but not sure about that.

**Comment by Gkiokan** [comment]
Same issue like [here](https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/14)

**Comment by imad-mest** [comment]
Hi I have the same problem did you find a solution ?

**Comment by Gkiokan** [comment]
Please check the [Troubleshooting Guide part d and e](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#i-get-timeout-error)

Maybe soon we can get an update from RPIOOSDK which could fix that issue.

**Comment by Gkiokan** [comment]
@EnekoT2001 As my assumption was correct It has somthing to do with the latest GoldHen 2.0b2 update.

Just use the old GoldHen 2.0 payload. Example from [Night King Host - https://www.nightkinghost.com/](https://www.nightkinghost.com/)
