### ISSUE TITLE
RPI OOP Port

### ISSUE THREAD

**Issue by EkkiBrue** [Gkiokan/ps4-remote-pkg-sender#13]
Any chance making your tool work with  [RPI OOP](https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK ) ?
Do you have plans making this happen ?

Thanks for your efforts!

**Comment by Gkiokan** [comment]
Yup. It is called RPI OOSDK, and yea not only that.
I am also preparing to support for IPI.

![image](https://user-images.githubusercontent.com/7249224/150638676-ade725bb-d930-4ace-812c-0f46c82d463e.png)

**Comment by Gkiokan** [comment]
I've talked to backporter (aka kernel panic) and as we are at the same spot this will go hand in hand. 
Don't worry for now. In version 1.0 the enpoints are also the same. Means it should work without trouble.  

But unfortunatelly there is no benefit yet using it. Upcomming updates will be benefitical.  
  
Feature Ideas are already set in the [issue on the RPI OOP](https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK/issues/1)
