### ISSUE TITLE
Queue Scanner

### ISSUE THREAD

**Issue by Gkiokan** [Gkiokan/ps4-remote-pkg-sender#18]
- [ ] Create Options (Step by Step, max 3 concurrent, manualy)
- [ ] Check current running tasks and limit it regarding choosen queue scanner option
- [ ] Autostart next item in the queue when finished previous one

**Comment by Pharaoh2k** [comment]
Thanks for your amazing program.
This is probably one of the most important features to add. +1

**Comment by Gkiokan** [comment]
As stated in my last commit on #11.  

[Queue Scanner in action](https://www.instagram.com/p/Cb05rXDj785/)  will be available in v2.7.0 (comming soon)
