### ISSUE TITLE
Error 2157510920

### ISSUE THREAD

**Issue by blablagaming** [Gkiokan/ps4-remote-pkg-sender#20]
When trying to install any package i get this error. Tested in both 2.4.3 and 2.5.0, same result. Both check server and check ps4 pass.

![image](https://user-images.githubusercontent.com/6634272/151645517-276af2ae-4b8a-4d93-a246-c7ca37a6195b.png)

**Comment by Gkiokan** [comment]
This error is not even in the [PS4 Wiki Database](https://www.psdevwiki.com/ps4/Talk:Error_Codes).

Does this error happens on other files, too?  
Have enough free Storage?  
Does the app exists already as a chunk or dead download? (check messages)

**Comment by blablagaming** [comment]
I think it may have been storage space, i uninstalled a game and it started working again.

**Comment by Gkiokan** [comment]
Thanks for the reply. I will add that to the Error Messages.
