### ISSUE TITLE
High memory usage and cpu usage

### ISSUE THREAD

**Issue by janisslsm** [Gkiokan/ps4-remote-pkg-sender#22]
Sometimes the app fails to launch but a process in the background is left which for some reason has high memory usage.
I'm on windows 10 x64 and using the portable version v2.4.2
![image](https://user-images.githubusercontent.com/97699850/151763875-5ef9483b-65dc-4321-ab29-93596e0aecf0.png)

I just noticed v2.5.2 beta was released so I will try seeing if I can get the same problem with that

**Comment by janisslsm** [comment]
I tried v2.5.2 and so far I've managed to get it with CPU this time
![image](https://user-images.githubusercontent.com/97699850/151765059-550dbadf-fc22-4f36-8ef3-bb10862e1adb.png)

**Comment by janisslsm** [comment]
Alright. I just don't get that memory or CPU usage normally unless the app glitches out and doesn't open.

**Comment by Gkiokan** [comment]
There is one thing to note. If you use the portable version on windows it actually extracts the content to temp folder and reads all the time from it. That may cause some cpu issues as windows is known for his high cpu usage on read processes.  

The same happend to me back on my windows times when windows tried to permanently to download updates. 
Having an SSD kills this issue but still, microsoft is very special in such cases.  

Just to verify. Could you try the the unpacked version within the *-win.zip file, too?

**Comment by janisslsm** [comment]
Will give it a try in a bit!

**Comment by janisslsm** [comment]
Unpacked version doesn't have that issue

**Comment by Gkiokan** [comment]
Well then it has to do with the temp handling of windows. I guess you still haven an HDD then?

**Comment by janisslsm** [comment]
No, I'm on a SSD

**Comment by Gkiokan** [comment]
Can you compare your cpu usage now?
Mac is kinda special with the application folders but here are my usages.

![image](https://user-images.githubusercontent.com/7249224/152132419-be8decbd-af49-4232-b503-16e2567d3667.png)

**Comment by janisslsm** [comment]
![image](https://user-images.githubusercontent.com/97699850/152132534-95122e74-bae6-4d7d-b66d-65676e97b162.png)
It just somewhere between 0% to 2.4%

**Comment by janisslsm** [comment]
I'm sending a package right now and getting 5-10% usage

**Comment by janisslsm** [comment]
![image](https://user-images.githubusercontent.com/97699850/152132902-6f5241d8-223f-4f78-a35c-7c5626af2367.png)

**Comment by Gkiokan** [comment]
That is pretty fair as the server needs to read your PKG file and serve it to the PS4.

Interesting. So the issue for the portable is just the temp handler of windows. I will take a look into that.  
I would suggest you to use the unpacked version then if you have still cpu usage problems on the portable one.  

I am not sure how to configure windows (as I left windows years ago) to optimize it.
But I can remember some optimization stuff back on windows7 where you could setup priority on hdd or ram .... not sure about that but something like that was available on my windows times.

**Comment by janisslsm** [comment]
Alright. I'll use the unpacked version for now. The portable version works fine but sometimes it fails to open and ends up using lots of CPU

**Comment by Gkiokan** [comment]
Unfortunatelly this is how windows handels portable versions when it puts all the executable data into the memory + temp folder.  
I guess portable one is more suites for pc's with a bit more power on the back.

**Comment by janisslsm** [comment]
What counts as more powerful. I wouldn't say my PC is low end.

**Comment by Gkiokan** [comment]
My Mac is not an comparable candidate but I have an i7 2,6GhZ with 16GB of RAM that works well.  
However Windows again is performing different on the same hardware. 

I will try to benchmark the portable version once the updates for 2.6 are done and I am testing it on my lenovo i5 ... 5th gen? dunno.

**Comment by janisslsm** [comment]
Alright. I'm on a Ryzen 5 2600 with 16GB x 2 of RAM (32GB total) so it shouldn't be a bottleneck

**Comment by Gkiokan** [comment]
You are right. You are on a stable base. [cpu comparision](https://www.cpu-monkey.com/de/compare_cpu-amd_ryzen_5_2600-vs-intel_core_i7_9750h)

Then it is based on Windows. I will take a look and try my best to get the best out of it for windows.  
Most fixes since release was only for windows lol.
