### ISSUE TITLE
Option to disable “minimize to tray”

### ISSUE THREAD

**Issue by valters-tomsons** [Gkiokan/ps4-remote-pkg-sender#25]
Hi, kudos for keeping the project alive! :upside_down_face: 

Any chance for an option to disable the app tray icon and kill the server whenever I close the main window?

**Comment by Gkiokan** [comment]
It's not a bug, it's a feature. This prevents users to close the server by accident.  

Actually if you Quit the Application through the Menu, it should be gone.  
The same goes for the process and the tray icon.
