### ISSUE TITLE
[feature] Show notification for progress

### ISSUE THREAD

**Issue by davigamer987** [Gkiokan/ps4-remote-pkg-sender#26]
On some apps (On kde) they have a notification indicating progress, i think this would be a nice thing to add

**Comment by Gkiokan** [comment]
Is already on my todo. I will continue next week with the updates, so stay tuned.

**Comment by Gkiokan** [comment]
Systemwide Notifications are implemented in the latest version [v2.7.1](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.7.1). Checkout the Releases.
