### ISSUE TITLE
Invalid value for 'task_id' parameter specified.? Need help

### ISSUE THREAD

**Issue by valianliu** [Gkiokan/ps4-remote-pkg-sender#27]
Thx for developer's effort. While using this software, I come across the following problem needs help.
environment: PS4 Pro 9.0 Firmware
Using Remote Package Installer Open Orbis Port by backporter

All DLC PKG are fine.
But the Base PKG, always come across task id=-1 
like this
![Snipaste_2022-02-23_13-36-58](https://user-images.githubusercontent.com/9492905/155267126-701bcb42-b674-4466-a979-ac8efb9b6a3b.jpg)
Notice is "Invalid value for 'task_id' parameter specified."
What should I do?
What's the problem.
Needs help Thx
Thx

**Comment by valianliu** [comment]
I tried original version of ps4_remote_pkg_installer
It works fine.

![Snipaste_2022-02-23_15-11-19](https://user-images.githubusercontent.com/9492905/155275226-1224a414-2933-4ff2-85e7-7d4d8019bcf1.jpg)

Not sure about whose problem. Is it

**Comment by Gkiokan** [comment]
I already commented on the [RPI OOSDK](https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK/issues/4) this is a bug with the RPI OOSDK.  

As mentioned backporter needs to debug this error down as it works with the original RPI from flatZ.  
  
I guess there is an error starting the install process and therefore it can't attaching a valid Task ID.  Task ID's are always > 1.
