### ISSUE TITLE
[BUG] Doesn't close?

### ISSUE THREAD

**Issue by HardRom** [Gkiokan/ps4-remote-pkg-sender#3]
W11
Ending process isn't enough, also had to go to Task Manager-Users-%USER%-"Manage and send PKG..." and disconnect it.
![image](https://user-images.githubusercontent.com/277477/147892406-ed986650-9362-446a-b305-31d597f28f2d.png)

**Comment by Gkiokan** [comment]
Application should still be active if you close all windows,   
this is intended to prevent accidently closing the application (which would kill the server).

To close the App you should Quit it through the Menu `Application > Quit`.

The Quit method closes all windows, shutdown the server and should also kill all processes.

I don't have a W11 running yet, but will give it a shot when I have a Win 11 device.

**Comment by Gkiokan** [comment]
@HardRom is this issue fixed for your case?

**Comment by Gkiokan** [comment]
I guess with the latest version and the deep logger there should be no errors anymore.
Latest version is also tested already by a couple of users on windows. 

If anything happens, feel free to open a new issue.
