### ISSUE TITLE
Linux build broken

### ISSUE THREAD

**Issue by valters-tomsons** [Gkiokan/ps4-remote-pkg-sender#31]
**Version:** PS4.Remote.PKG.Sender.V2-2.7.1.AppImage
**OS:** Arch Linux

Just updated from 2.5.2, but the newest version seems to have issues with linux. 

1. I seem to get mac-os window decorations
2. None of the navigation (or decoration) buttons work, only the buttons inside the page work ("Reset Options", "Check Options" etc.)

![Screenshot_2022-04-03-45_1321x816](https://user-images.githubusercontent.com/4209639/161423356-5b6b7bec-cc67-41a1-9cda-25a90fb7fb5e.png)

Buttons in the tray work, so do the windows for logs and information.

**Comment by Gkiokan** [comment]
Can you open the Info window and show me what the values of platform for you is?
I removed the OS Frame and build a custom Titlebar to get Darkmode on it working, so there is either a mac-os style or a windows like Title Bar.

The navigation should work os across the same as the base is rendered for chromium. Interesting. 
Maybe this is a special thing on linux, because I have set the Navigationselement as draggable, too.

**Comment by pepitopajas** [comment]
chmod: cannot access '/opt/PS4 Remote PKG Sender V2/chrome-sandbox': No such file or directory

**Comment by Gkiokan** [comment]
@pepitopajas I don't think you would need Chrome for that as it is a standalone and packs chromium with itself. 
However I think this sounds more like an security issue. Check your firewall or priviledges on the app.  

@valters-tomsons  Could you try this version here. I disabled the dragging element. Which I guess makes the trouble on linux. [v2.7.1-nodrag-on-menu](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/download/v2.7.1/PS4.Remote.PKG.Sender.V2-2.7.1-nodrag-on-menu.AppImage)

**Comment by Gkiokan** [comment]
@valters-tomsons I've re-reuploaded the whole build with the draggable fix.  
Tested on windows, it works. I am not able to test Linux yet but it seems only to be a issue on non-mac distrubutions in combination to that draggable area.  However it should be fully fixed for now.  

[Re-build and re-uploaded Release v2.7.1](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.7.1)

**Comment by valters-tomsons** [comment]
Works good and looks beautiful, great work!
