### ISSUE TITLE
(DLC / pkg with no params) Small PKG 128KB - Error 2157510660

### ISSUE THREAD

**Issue by DesignPixelZ** [Gkiokan/ps4-remote-pkg-sender#41]
I was able to install install the PKG via USB, but, it always failed when I tried using the PKG sender.

**Comment by Gkiokan** [comment]
Is it probably a DLC? The error code means `SCE_BGFT_ERROR_INVALID_ARGUMENT `  
Some DLC's has problems to be installed though the Package Installer (RPI on your ps4 from flatZ).  
You may try the other RPI which are patched with Open Orbis Tools.

**Comment by Gkiokan** [comment]
Cyb1k has also reported that some patches are not able to be installed due the missing params.   
So unfortunatelly this must be fixed either on the installer or the patched pkg files itself.  
  
I got this on my todo list for the features, to patch the files maybe if necessary.

**Comment by Masamune3210** [comment]
it isnt something that can just be patched unfortunately, the correct params have to be present for the game to know that the DLC is installed and for the system to mount it correctly. Sounds like more research has to be done in how the download system works, because nothing should be triggering a invalidarg in bgft unless the file is legitimately corrupted

**Comment by Gkiokan** [comment]
True but cybik explained that once. For some patches or backports there are just no or not enough sfo params set and therefore they doesn't work with the RPI and fail to install. I thought a simple patch of that pkg's would probably fix them. Something like applying the missing params on top of the existing ones so it could work. This is just an assumtion. Not tested yet though.

**Comment by DesignPixelZ** [comment]
> Is it probably a DLC? 
Yes, it was a DLC. And I think you’re right about missing parameters. When I checked the DLC it doesn’t even have a name or picture and it shows at “?”. Tho is works without a problem. I think is common practice for some DLC’s as I’ve seen this before. If needed I can provide the fake pkg.

**Comment by Gkiokan** [comment]
All fine. I can get some from Cyb1K as he was reporting about that issue and all pkg sender has the same problem.  
I will see what I can do regarding the patches. Stay tuned for now.

**Comment by Gkiokan** [comment]
Btw, this issue can be fixed if the DLC's are build with params.   
There are couple tools that does that.   

Nothing related to the app itself. So either the DLS's are fully correct or you need to patch them yourself to be compatible with the PKG Sender and Installer.

**Comment by dephunk** [comment]
Just for anyone who see's this & is having a problem with DLC's without params - easiest solution is to used PS4 Xplorer 2.0 and install it via a USB stick.

**Comment by quickplaymobile** [comment]
Problem still exists and I'm facing it sometimes. You can use PS4 Xplorer 2.0 as mentioned above or simply use an USB Stick and install from goldhen menu.
