### ISSUE TITLE
Web interface option

### ISSUE THREAD

**Issue by valters-tomsons** [Gkiokan/ps4-remote-pkg-sender#45]
Would it be possible to expose current UI over a web interface? (started headless, as a system service)
 
I'd like to host this on my NAS since my package backups are stored there, would make installing packages a lot easier.

**Comment by Gkiokan** [comment]
I have already planed a Chrome Extension and an mobile app for it. 
So it's not getting in the way and could be used out of your space. 
So yea, this is something coming for sure. 

The other features itself are on a higher priority that has to be done.  
If you'd like to try out, you could try the HB-Store CDN and CLI version that I've created.
They are working with the HB-Store itself and you can install directly on your ps4.  

One of them both are on already on the support list of RetroArch
(HB-Store CDN Server)[https://github.com/Gkiokan/hb-store-cdn-server]. 
(HB-Store CDN CLI Server)[https://github.com/Gkiokan/hb-store-cdn-cli-server].

**Comment by valters-tomsons** [comment]
Thanks, didn't know about cli server
