### ISSUE TITLE
[feature] Bulk selection/deselection

### ISSUE THREAD

**Issue by Pharaoh2k** [Gkiokan/ps4-remote-pkg-sender#48]
Love your app, the RC works great!
A bulk selection/deselection feature would really be useful.
I just had a folder with 236 DLC files and being able to select and deselect all/part of them would have been much more efficient than clicking them all one by one. :)
![CQWBbzn](https://user-images.githubusercontent.com/5753365/182410611-d802ad07-f121-48c1-8a63-a7330b39a241.png)

![AyUUQlj](https://user-images.githubusercontent.com/5753365/182411118-c1c20a11-ab79-466c-a16c-4365dd46849e.png)

**Comment by Gkiokan** [comment]
This is planed already as some user has reported that to me back on discord. 

There is also a "grouping" function planed so each Title will have all it's content split up in base, update, backport, dlc, etc. 
Each of them will get a new context menu option to trigger individual actions on the selected group.

**Comment by ifelixculpa** [comment]
> This is planed already as some user has reported that to me back on discord.
> 
> There is also a "grouping" function planed so each Title will have all it's content split up in base, update, backport, dlc, etc. Each of them will get a new context menu option to trigger individual actions on the selected group.

awesome sir waiting for this awesome tool to get more awesome :)

**Comment by jonibim** [comment]
@Gkiokan Has this feature been already worked on? Otherwise I can have a look to at least add an Add all/Remove All button.

**Comment by Pharaoh2k** [comment]
[**@jonibim**](https://github.com/jonibim) commented on [Aug 9, 2023, 4:19 AM GMT+7](https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/48#issuecomment-1670321767 "2023-08-08T21:19:09Z - Replied by Github Reply Comments"):
> @Gkiokan Has this feature been already worked on? Otherwise I can have a look to at least to add an ```Add all``` / ```Remove All``` button.
> 
> _Originally posted by @jonibim in https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/48#issuecomment-1670321767_

Honestly, the dev seems quite busy with other RL projects and there hasn't been any development for a long time, so if you can fork this great open-source project, improve it and release it publicly- that would be really nice. :)

**Comment by Masamune3210** [comment]
Gonna have to be careful if you intend to have special behavior or sorts involving backports, since they appear exactly like a normal update, save for a different passcode which you (at least not easily) can't programmatically detect

**Comment by Gkiokan** [comment]
Preparing a couple things and let you know there are some progress guys.
The Bulk add Button is probably the easiest one to do, but I want the Drag and Drop feature to be in the next update, so working on that is a bit tricky due the different paths. But this again needs another feature for handling different paths, so this means there will be a Setting or some sort of tabbing in the Server Tab which allows you to add multiple paths as sources. Problem with that will be duplicated paths (just in case someone adds dumb paths duplicated), so this needs another fix before the update comes.  
  
But this comes handy for the next feature of sharing your Host to other Users as well.  More infos on the next next update when I am ready for it.  

<img width="495" alt="image" src="https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/7249224/4f697f94-a20e-4285-a9d8-b6cf89de5de4">
<img width="1260" alt="image" src="https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/7249224/48f959dd-da6d-4705-b164-d445a7f65d04">
<img width="1281" alt="image" src="https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/7249224/4c1541ff-959c-4ba4-98a2-d3e6a0e3b0c3">

**Comment by Gkiokan** [comment]
I think this looks pretty decent now. Testing with large folders and sub scans if the dragged item is a folder.  
<img width="1267" alt="image" src="https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/7249224/dd43f413-4f38-4fca-a757-4642adb0a531">

**Comment by Gkiokan** [comment]
@Pharaoh2k Mate, your Bulk action request is done. 
Also the whole Drag and Drop from files and folders from any place works like a charm. 

Check out the latest Version [Remote Package Sender v2 (v2.9.1)](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.9.1)
