### ISSUE TITLE
program window size

### ISSUE THREAD

**Issue by motaha84gamer** [Gkiokan/ps4-remote-pkg-sender#49]
the size of the program is to big that always the last pkg i want to install goes under the taskbar and its not accessible if its possible change the size in the next update tnx bro.
![Screenshot 2022-08-15 095443](https://user-images.githubusercontent.com/111265910/184581017-ca9c3f11-f826-47f3-9703-b30aba14e431.png)

**Comment by Gkiokan** [comment]
I am currently working on the hotfixes, there will be an update within the next hours I think.  
Can you maximize the Window to have it fill your full screen?

**Comment by Gkiokan** [comment]
In the next update there will be more space to the bottom end as there will be a new back to top button if you scroll down.  
Have a sneak peak screenshot below: 

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7249224/184705297-20cc0e8a-4dbf-4647-a9f9-f19a553b52c2.png">

**Comment by Gkiokan** [comment]
Please checkout the new Release. It should match for your case now. 
[Remote Package Sender v2 (v2.8.0](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.8.0)
