### ISSUE TITLE
Upload speed suddenly slow.

### ISSUE THREAD

**Issue by lordthuy941792** [Gkiokan/ps4-remote-pkg-sender#52]
I don't know what went wrong: my PS4, my PC or the app. Upload speed usually 50-60mbs now slows down to 11mbs.

**Comment by lordthuy941792** [comment]
Nevermind. I restart the PS4, the app and the download speed returns to normal. I figure that must be the ps4cheater I used the last time.

**Comment by Gkiokan** [comment]
Sometimes a restart does wonder :) Good to hear you solved it.  
This may be a hint for other users when they struggle on speed suddenly.
