### ISSUE TITLE
macOS13 bug

### ISSUE THREAD

**Issue by qin9125** [Gkiokan/ps4-remote-pkg-sender#53]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/32502941/196565878-d670b36b-d20c-4b25-95ff-3bae69ab916d.png">

**Comment by Gkiokan** [comment]
Did you accidentally plug it out the drive? The app should have access to everything that you can reach with your user on your mac.  If it's a harddrive, try to re-plug and select it then as server path again.

**Comment by qin9125** [comment]
> Did you accidentally unplug the drive? The app should have access to everything that you can reach with your user on your mac. If it's a harddrive, try to re-plug and select it then as server path again.

thank you
