### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by Aruscha** [Gkiokan/ps4-remote-pkg-sender#54]
Beim installieren von einem Update eines Spiels wie bei einem addon ist ein Fehler aufgetreten.
Problem ist, er sagt die Datei sei vorhanden. Im Spiel aber nicht. Weil... Ist ja ein Fehler aufgetreten...

Wie kann ich die Datei jetzt neu installieren? 🤔

An error occurred while installing an update of a game like an addon.
Problem is, he says the file exists. But not in the game. Because... An error has occurred...

How can I reinstall the file now? 🤔

**Comment by Gkiokan** [comment]
Schau mal, ob die Datei wirklich einen Fehler hat oder es nur ein Installationsfehler war?   
Bei manchen DLC's fehlen die Header Dateien, die dann nicht über die Package Sender installiert werden können (technisch nicht möglich, da Sachen fehlen), da ist der einzige Workaround über USB soweit ich weiß.  

Was eventuell auch sein kann ist, dass dein Update ein Package Lost hat und nicht Vollständig war, bevor du es installiert hast, passiert bei partiellen Downloads manchmal, wenn der merge dann nicht 100% ist.  

Zum Überprüfen sollte ein ps4 PKG Viewer reichen. Hab das meinerseits erst ab v2.9.x geplant, aber komme dieses Jahr nicht mehr dazu alles zu updaten.

**Comment by Aruscha** [comment]
Hab das ganze jetzt mal über USB gemacht...
Hat funktioniert. 

 Wundervoll ist, dass durch das Update was ich installieren wollte, das Spiel nicht mehr startet.

Kann ich das Update wieder irgendwie deinstallieren?

**Comment by Gkiokan** [comment]
Ich glaube nur, wenn du das ganze Spiel deinstallierst. Hatte ich auch mal, weil mein Update nicht Backported war für 5.05, dann kriegst halt den Fehler. Oder du überschreibst das update mit dem passenden Update für deine FW.
