### ISSUE TITLE
 Unexpected element value of parameter 'packages'.

### ISSUE THREAD

**Issue by Kayz0718** [Gkiokan/ps4-remote-pkg-sender#55]
I get this error when i try to download a game using a URL from https://filecrypt.co/

**Comment by Gkiokan** [comment]
Probably a Captcha Issue on filecrypt as it forwards the links.  
Try to add the direct link of the PKG.  
If that doesn't work try to download the file and install it. When this works you know it's caused by the forwarding urls.

**Comment by Kayz0718** [comment]
how can i add the direct link?

**Comment by Gkiokan** [comment]
Either decrypt the links or put the links in jDownloader and copy the direct link of the PKG file.    

Or you can [DirectPackageInstaller](https://github.com/marcussacana/DirectPackageInstaller) from markus which has a bit more support of external links and even a proxy feature as I know.  

Usually the add links feature does work on my app but there are no logic behind a Hoster proxy that decrypts links. Ofc I would need to check that in detail to be sure what exactly is the issue but I know if I add a direct Link from a Host that is publicly available, then it works. FTP, Server, Host, IP/Path:port, etc.

**Comment by Kayz0718** [comment]
okay thank you i used DirectPackageInstaller with

**Comment by Kayz0718** [comment]
thank you i used DirectPackageInstaller and a vpn an it worked
