### ISSUE TITLE
Slower install as before by the same connection???

### ISSUE THREAD

**Issue by XRazeYT** [Gkiokan/ps4-remote-pkg-sender#68]
since the update where the PS5 support was added the installation of the games on the ps4 is extremely slow 7gb at 50min+ before it was 5min

**Comment by Gkiokan** [comment]
I refactored the Request calls to the ps4, but didn't touch anything besides that.
Means it must be something with your Network. Another user had the same issue and his issue was because his ps4 connected to the WLAN via 2.4GhZ instead of 5GhZ.

Could you check your network?

**Comment by Gkiokan** [comment]
I guess it was just the changed Network Interface. I'll close this for now. If this issue still exists, gimme a call.
