### ISSUE TITLE
Can't send Fpkg More the 100G!

### ISSUE THREAD

**Issue by imedox** [Gkiokan/ps4-remote-pkg-sender#69]
i test to send fpkg on ps5 that have more then 80g that not work get time out error, work great on 1/40gb fpkg.

**Comment by Gkiokan** [comment]
I guess we need to debug on our side what happens here exactly.  

Feel free to join the [PKG-Zone Discord Server](https://discord.com/invite/fcUg6yP5Gy) and Report that directly on Support, so @LightningMods can see it directly with proper investigation. We will also need some Information like what Network Interface are you using, FW Version, etc. etc.

**Comment by Gkiokan** [comment]
There was no response anymore since then. So I think it has been worked out somehow? 
I will close this as it doesn't seem to be a problem anymore.
