### ISSUE TITLE
"The graphical interface doesn't start when installing from a .deb file on Debian 12."

### ISSUE THREAD

**Issue by orabeidm** [Gkiokan/ps4-remote-pkg-sender#76]
"The graphical interface doesn't start when installing from a .deb file on Debian 12."

**Comment by Gkiokan** [comment]
Is this on the latest release v2.10.4?

**Comment by orabeidm** [comment]
dmor@deb12:~/Загрузки$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
dmor@deb12:~/Загрузки$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
dmor@deb12:~/Загрузки$

**Comment by orabeidm** [comment]
dmor@deb12:~/Загрузки$ uname -r
6.1.0-21-amd64

**Comment by Gkiokan** [comment]
> dmor@deb12:~/Загрузки$ ps4remotepkgsenderv2 (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false". It will change to be "true" in Electron 9. For more information please check [electron/electron#18397](https://github.com/electron/electron/issues/18397) [1424516:0523/202524.997118:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye. Ловушка трассировки/останова

Thanks for the report. I will check that soon.

**Comment by Gkiokan** [comment]
@orabeidm Could you try to run the application with the flag `--no-sandbox` and test if this workaround works?  
In your case `ps4remotepkgsenderv2  --no-sandbox`

**Comment by orabeidm** [comment]
dmor@deb12:~$ ps4remotepkgsenderv2  --no-sandbox
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
::store | no path given for base_path
![image](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/60073650/6b7dbd24-361b-41c2-9d4d-fbfd0aaa0126)


It has launched. I'll figure out how to work with it and test it. Right now, I'm uploading games via FTP. If there are any more errors, I'll describe them. Thank you!

**Comment by Gkiokan** [comment]
Thanks for reporting back. The Log messages are ok and not to worry.  
You can have a look into the latest Modded Warfare Video he explains it a bit how and what. 

[Installing PS4 Apps remotely over the Network on 11.00](https://www.youtube.com/watch?v=BjvHCDmOZ0o)
