### ISSUE TITLE
Error 2157510790.

### ISSUE THREAD

**Issue by Osmium00** [Gkiokan/ps4-remote-pkg-sender#80]
After making certain everything is set up correctly, I get the "Error 2157510790." I can't find documentation on this error code anywhere. Thank you for any and all help!
![image](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/135172757/477fc278-1501-4b40-a5d3-de502d8e1e17)
^ Testing my connection ^
![image](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/135172757/4e4bd780-4417-464f-ad52-d3fe53660a26)
^ When I press "Start" ^

**Comment by Gkiokan** [comment]
This error code is actually not documented.  Can you check if you have enough Storage space and if the game is alraedy existing on your device? Maybe check Notifications and delete all referencing Assets and delete them when you can find and try again.  
 
I will research von that Error Code 2157510790 to find out what it means.

**Comment by Gkiokan** [comment]
Thanks to @LightningMods we can clarify that now.
![image](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/7249224/da36c901-a400-479b-9696-7a1920f48d82)
  
 The Solution to this is as I've wrote before to cleanup all Notifications and Data for that PKG and try again.
