### ISSUE TITLE
Crash on start with PS4.Remote.PKG.Sender.V2-2.10.4.AppImage

### ISSUE THREAD

**Issue by cnapieral** [Gkiokan/ps4-remote-pkg-sender#82]
With the latest version 2.10.4.AppImage, application is crashing on start. 

Following the error log:

Gtk-Message: 19:14:55.425: Failed to load module "colorreload-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
::store |
Read files at base path  /XXX/XXX/backup/roms/ps4/
Loading Files from Subdirectory true
Loading Directory files in  /XXX/XXX/backup/roms/ps4/
[1565588:0611/191457.356451:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

2.10.3.AppImage runs fine

**Comment by Gkiokan** [comment]
Did that happen on the latest Version only or on previous ones, too?
Try starting the application with the `--no-sandbox` parameter.  

Maybe this is a linux thing. Happend to .deb release too. #76 

Will definetely implement it as a fix in the upcoming version.

**Comment by cnapieral** [comment]
Thanks bro! It is working with --no-sandbox switch.

regards and thanks for your great work,
Chris

**Comment by Gkiokan** [comment]
You're welcome man. Have fun with the app. And by any means, if you like it, shoot a ko-fi support :)   
(I don't like ads)
