### ISSUE TITLE
Not installing pkg

### ISSUE THREAD

**Issue by SeMuh83** [Gkiokan/ps4-remote-pkg-sender#84]
Hi,

using latest version of sender

PS4 pro 9.00

Bin loader activated and program can connect to PS4 console.

But if pressing play button for install a pkg nothing happens.

I just receive a notification on my PS4 that a payload was received from my PC's ip address. That's it.

Tried different pkg files.

Log is not saying anything

1719603114484 | Pummel Party [CUSA18824] [v01.00].pkg error on install
1719603114483 | Pummel Party [CUSA18824] [v01.00].pkg install
1719603114474 | Install Request
1719603114474 | Pummel Party [CUSA18824] [v01.00].pkg prepare start installing
1719603111862 | PS4 is accessible

**Comment by Gkiokan** [comment]
BinLoader isn't supported yet.  
You have to have RPI running (have it open) on your PS4 when you start the Installation Process.
