### ISSUE TITLE
Black Window on Linux (needs --no-sandbox)

### ISSUE THREAD

**Issue by b2ag** [Gkiokan/ps4-remote-pkg-sender#86]
Hi,

PS4 remote pkg sender is a really handy tool but it stopped working for me (shows only a black window) since I switched from Xorg to Wayland. It looks like the four years old Electron version might be the culprit. Is it possible to update to a more recent Electron version?

Best

EDIT:  Using "--no-sandbox" parameter as a workaround makes it render again.

**Comment by Gkiokan** [comment]
The --no-sandbox parameter is the most apprently fix for Linux Distributions as it seems to make trouble with the default renderer on the gpu drivers.  

However there is an update planed that should add no-sandbox on linux detection automatically.

**Comment by b2ag** [comment]
Thanks for the info. I can confirm that a Electron App I use very often (Freetube) is also setting --no-sandbox as does another one using NW.js. Did not know that. Changed the issues title to reflect your proposed solution.
