### ISSUE TITLE
-2143223530 error on MacOS 15 beta

### ISSUE THREAD

**Issue by cambarnes7** [Gkiokan/ps4-remote-pkg-sender#88]
Getting this error when trying to install any pkg file on ps5 with etaHEN 1.8.

**Comment by Gkiokan** [comment]
Sorry for the delay. Was on vocation. 

We will check this on PKG-Zone with @LM

**Comment by Gkiokan** [comment]
This specific error code is not listed yet. Could you solve this Issue?
Could it be less drive space, Already installed or broken PKG maybe?
Or not compatible FW?

**Comment by cambarnes7** [comment]
Hey, I just tried this again, 4.03 PS5 on etahen 1.8.  At first I was getting a similar -214xxxxxxx error but looking at my config again, I noticed that my mac local ip had changed even though looking at my router it still showed me the old ip.  After changing the ip and restarting the server, everything seems to be working perfectly now.
