### ISSUE TITLE
Encoding failure ubuntu 24.04

### ISSUE THREAD

**Issue by Svarshick** [Gkiokan/ps4-remote-pkg-sender#90]
I can't use app because of this issue
![image](https://github.com/user-attachments/assets/8ed35f9c-a6f8-4d0b-85f7-89c67c798a5e)
I tried to add file manually, but it didn't see file

**Comment by Gkiokan** [comment]
Which Linux Distro and Version are you using?

**Comment by Svarshick** [comment]
> Which Linux Distro and Version are you using? *Ubuntu 24.04
> 
> Any Special Language maybe? I never saw this error before.

I am sorry, but I can't say you exactly. I have already change my os. I remember that I had only english us and russian language. I have doubts about blaming russian locale

**Comment by Gkiokan** [comment]
Can't relate either as the Frontend Fonts on the App seems to be fine.  
It might be some broken internal chromium version with your language selection - which shouldn't be but could be.  

I think this was an exceptional use-case and I guess you are doing well right now. Have fun with it :)
